# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10

env:
  - DESTINATION='platform=iOS Simulator,name=iPad Retina'
  - DESTINATION='platform=iOS Simulator,name=iPhone 5'
  - DESTINATION='platform=iOS Simulator,name=iPhone 6'
  - DESTINATION='platform=iOS Simulator,name=iPhone 7'

script:
  - set -o pipefail && xcodebuild -workspace Example/RevealMenuController.xcworkspace -scheme RevealMenuController-Example -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
